# We deliberately don't use travis's language=python option because
# we install miniconda and use conda to get python. Additionally, 
# Travis's auto-install of python doesn't work on osx images (see
# https://github.com/travis-ci/travis-ci/issues/4729).
language: generic

sudo: false

before_install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  # brew-installed geos interferes with cartopy?
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew uninstall --ignore-dependencies geos gdal postgis;
    fi

jobs:
  include:
    - install: scripts/ci/install_examples
      script: scripts/ci/test_examples
      os: linux
      env:
      - GROUP=examples
      - PYTHON_VERSION=3.6
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      os: linux
      env:
      - GROUP=unit
      - PYTHON_VERSION=2.7
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      os: linux
      env:
      - GROUP=unit
      - PYTHON_VERSION=3.5
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      os: linux
      env:
      - GROUP=unit
      - PYTHON_VERSION=3.6
    - install: scripts/ci/install_examples
      script: scripts/ci/test_examples
      os: osx
      osx_image: xcode8.3
      if: branch = master AND type != pull_request
      env:
      - GROUP=examples
      - PYTHON_VERSION=3.6
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      os: osx
      osx_image: xcode8.3
      if: branch = master AND type != pull_request
      env:
      - GROUP=unit
      - PYTHON_VERSION=2.7
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      os: osx
      osx_image: xcode8.3
      if: branch = master AND type != pull_request
      env:
      - GROUP=unit
      - PYTHON_VERSION=3.5
    - install: scripts/ci/install_unit
      script: scripts/ci/test_unit
      os: osx
      osx_image: xcode8.3
      if: branch = master AND type != pull_request
      env:
      - GROUP=unit
      - PYTHON_VERSION=3.6
#    # TODO this is just temp
#    - install:
#      - scripts/ci/install_examples
#      - conda install -c conda-forge sphinx beautifulsoup4 graphviz
#      - pip install sphinx_ioam_theme
#      - pip install -e .
#      script:
#      - cd doc
#      - nbsite_nbpagebuild.py nbsite ../examples .
#      - sphinx-build -b html . ./_build/html
#      - nbsite_fix_links.py _build/html
####
# add some kind of cleanup-for-deploy nbsite command...
       - rm -rf _build/html/*.inv
       - rm -rf _build/html/.doctrees
       - find _build/html -iname "*.ipynb" -exec rm {} +
       - rm -rf _build/html/_sources
####
#      - touch ./_build/html/.nojekyll
#      - 
#      - cd ..
#      os: linux
#      if: branch = docs
#      env:
#      - GROUP=docs
#      - PYTHON_VERSION=3.6
#
#deploy:
#  - provider: pages
#    skip_cleanup: true
#    github_token: $GITHUB_TOKEN
#    local_dir: ./doc/_build/html
#    on:
#      tags: true


notifications:
  email: false
